### ISSUE TITLE
Issue with jaxb-api.jar in class path of jaxb-core-2.2.7.jar

### ISSUE THREAD

**Issue by anilmaddipatla** [ahus1/hystrix-examples#2]
Hi 

I am new to the whole open source and hysterix. I am trying to run this sample on liberty server and when I deploy i get 2 kinds of exceptions 

1) about jaxb-api.jar and jaxb-core.jar being mentioned in classpath of some of the jars inside WEB-INF/lib/<jars>

2) @WebServlet and  @WebFilter missing "urlPatterns attribute or servletNames" attribute for rest easy jars of jboss.

The second one i think we can ignore given that we do not intend to invoke the servlets of jboss ( or am i wrong)

The first set is bothering me and I think is the reason why application is not deployed successfully.

---

[9/10/15 10:40:39:641 IST] 00000036 m.ibm.ws.container.service.app.deploy.ManifestClassPathUtils W SRVE9967W: The manifest class path jaxb-api.jar can not be found in jar
 file wsjar:file:/C:/WorkArea/Samples/hysterixsamples/liberty/wlp/usr/servers/hystrixsample/dropins/hystrix.war!/WEB-INF/lib/jaxb-core-2.2.7.jar or its parent.
[9/10/15 10:40:39:765 IST] 00000036 m.ibm.ws.container.service.app.deploy.ManifestClassPathUtils W SRVE9967W: The manifest class path jaxb-api.jar can not be found in jar
 file wsjar:file:/C:/WorkArea/Samples/hysterixsamples/liberty/wlp/usr/servers/hystrixsample/dropins/hystrix.war!/WEB-INF/lib/jaxb-impl-2.2.7.jar or its parent.
[9/10/15 10:40:39:766 IST] 00000036 m.ibm.ws.container.service.app.deploy.ManifestClassPathUtils W SRVE9967W: The manifest class path jaxb-core.jar can not be found in ja
r file wsjar:file:/C:/WorkArea/Samples/hysterixsamples/liberty/wlp/usr/servers/hystrixsample/dropins/hystrix.war!/WEB-INF/lib/jaxb-impl-2.2.7.jar or its parent.
[9/10/15 10:40:40:236 IST] 00000036 m.ibm.ws.container.service.app.deploy.ManifestClassPathUtils W SRVE9967W: The manifest class path jaxb-api.jar can not be found in jar
 file wsjar:file:/C:/WorkArea/Samples/hysterixsamples/liberty/wlp/usr/servers/hystrixsample/dropins/hystrix.war!/WEB-INF/lib/jaxb-core-2.2.7.jar or its parent.
[9/10/15 10:40:40:261 IST] 00000036 m.ibm.ws.container.service.app.deploy.ManifestClassPathUtils W SRVE9967W: The manifest class path jaxb-api.jar can not be found in jar
 file wsjar:file:/C:/WorkArea/Samples/hysterixsamples/liberty/wlp/usr/servers/hystrixsample/dropins/hystrix.war!/WEB-INF/lib/jaxb-impl-2.2.7.jar or its parent.
[9/10/15 10:40:40:261 IST] 00000036 m.ibm.ws.container.service.app.deploy.ManifestClassPathUtils W SRVE9967W: The manifest class path jaxb-core.jar can not be found in ja
r file wsjar:file:/C:/WorkArea/Samples/hysterixsamples/liberty/wlp/usr/servers/hystrixsample/dropins/hystrix.war!/WEB-INF/lib/jaxb-impl-2.2.7.jar or its parent.

---

Can you please help??

Regards
Anil

**Comment by ahus1** [comment]
I will have a look over the weekend.

**Comment by anilmaddipatla** [comment]
Thanks a ton

**Comment by ahus1** [comment]
I found two problems when using the example with Liberty: 
- Liberty is by default a full Web Profile as I understand it. Therefore the dependency `resteasy-servlet-initializer` conflicts with the automatic JAX-RS configuration. I added a new profile to `pom.xml` for Liberty.
- JAXB dependency is actually not used, therefore I removed it

I fixed these two issue in commit 52ade31adedd25d9c82c6df22b012a688f8c8cfe.

In order to build a WAR for Liberty, you'll need to set a profile for maven:

```
mvn -Pliberty clean package
```

The resulting WAR will includes also a Liberty specific configuration that the application is available at `/hystrixapp` once it has started (it takes about 45 sec on my local installation). My Liberty version identifies itself as "WebSphere Application Server 8.5.5.7". I used the out-of-the-box defaultServer.

I notice that the included Swagger installation doesn't work as expected, but this should not be problematic.

I was able to call the small REST implementation without problems from the browser and the included JMeter test.

I didn't find a solution to pass runtime information to archaius from an external file yet (see the included `setenv.bat` file). I tried to add a `set JVM_ARGS=...` just before the `server run` but that didn't work out. Maybe you can help out with some Liberty experience here.

**Comment by anilmaddipatla** [comment]
Hi Alexander,
             Can you please elaborate more on what do we intend to pass and
how are we intending to pass to archaius. If you can give me an example of
how its being done and how do u want to do it I can figure out a way. BTW i
deployed the latest version and it is working for me too. I have some more
things to discuss it might help a lot if we can discuss over a chat. Is
that possible??
Regards
Anil

**Comment by ahus1** [comment]
I'm no user of WebSphere, sorry...
